### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by ashioyajotham** [basetenlabs/musicgen-large-truss#1]
Whether logging in from cmd or from the notebook, it keeps returning a permission error pointing to the `.baseten_config` as still running. I can't figure out why.

**Comment by philipkiely-baseten** [comment]
Hi, just want to make sure I understand your question:

You get this error when running `baseten login`, right? And what operating system are you using?

**Comment by ashioyajotham** [comment]
> Hi, just want to make sure I understand your question:
> 
> You get this error when running `baseten login`, right? And what operating system are you using?

Yeah in the notebook. The error is pointed to that line. I use Windows 10

**Comment by philipkiely-baseten** [comment]
Thank you, will look into this!

**Comment by philipkiely-baseten** [comment]
I was able to reproduce the error on a fresh Baseten install on Windows 10 and I've identified the issue in the Baseten client. I'll work with an engineer to fix this and let you know as soon as a fix is out.

**Comment by philipkiely-baseten** [comment]
Hi again!

We found the issue, please try `pip install baseten==0.6.6rc1` to get a release candidate that will work on Windows, we will make a full release with the fix soon.

**Comment by ashioyajotham** [comment]
> Hi again!
> 
> We found the issue, please try `pip install baseten==0.6.6rc1` to get a release candidate that will work on Windows, we will make a full release with the fix soon.

Hello, hurrah! It worked. Thank you so much!
